In [4]:
import sys
import numpy as np


python_list = list(range(100 ))
lsit_size = sys.getsizeof(python_list[0]) * len(python_list)


numpy_array = np.arange(100)
array_size = numpy_array.nbytes
print(f"Size of Python list: {lsit_size} bytes")
print(f"Size of NumPy array: {array_size} bytes")

Size of Python list: 2800 bytes
Size of NumPy array: 800 bytes


In [10]:
import time
l1 = list(range(1_000_000))
l2 = list(range(1_000_000))


start = time.time()
print(start)

l3 = [x + y for x, y in zip(l1, l2)]

print(f"Python list computation: {time.time() - start} seconds ")

start = time.time()

A1 = np.arange(1_000_000)
A2 = np.arange(1_000_000)
A3 = A1 + A2
print(f"NumPy array computation: {time.time() - start} seconds ")

1751541161.9377797
Python list computation: 0.38953423500061035 seconds 
NumPy array computation: 0.015244245529174805 seconds 


In [2]:
import numpy as np


In [3]:
arr = np.array([1, 2, 3, 4,])
print(arr)

[1 2 3 4]


In [8]:
print(arr.shape)
print(arr.dtype)
print(arr.size)
print(arr.ndim)

(4,)
int64
4
1


In [12]:
#Operation on NumPy arrays

arr = np.array([1, 2, 3, 4])
print(arr + 10) # Add 10 to each element
print(arr * 2)  # Multiply each element by 2
print(arr ** 2) # Square each element
print(arr > 2)  # Compare each element with 2

[11 12 13 14]
[2 4 6 8]
[ 1  4  9 16]
[False False  True  True]


In [13]:
import numpy as np

# 1D array


a = np.array([1, 2, 3, 4, 5])
print("1D array: ", a)

1D array:  [1 2 3 4 5]


In [ ]:
type(a)


numpy.ndarray

In [17]:
# Create a 2D array
b = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print("2D array: ", b)

2D array:  [[1 2 3 4]
 [5 6 7 8]]


In [18]:
type(b)

numpy.ndarray

In [19]:
np.array([1, 2, 3, 4], dtype=float)

array([1., 2., 3., 4.])

In [20]:
np.arange(1, 11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [24]:
np.arange(1, 11, 2)

array([1, 3, 5, 7, 9])

In [ ]:
np.arange(1, 11).reshape(5, 2)#row, column

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [26]:
np.arange(1, 11).reshape(2, 5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
np.ones((3,4))# Create a 3x4 array filled with ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [29]:
np.zeros((3,4))# Create a 3x4 array filled with zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [30]:
np.random.random((3, 4))# Create a 3x4 array with random values between 0 and 1

array([[0.96509809, 0.69959159, 0.96377944, 0.51756118],
       [0.37254135, 0.65775838, 0.1910746 , 0.67844211],
       [0.03443022, 0.07885286, 0.47674827, 0.70776108]])

In [31]:
np.random.randint(1, 100)

58

In [32]:
np.random.randint(1, 10, (3, 4))# Create a 3x4 array with random integers between 1 and 10

array([[3, 8, 7, 7],
       [3, 2, 5, 2],
       [3, 1, 8, 4]], dtype=int32)

In [35]:
##seed

np.random.seed(50)  # Set a seed for reproducibility
np.random.randint(1, 100, 10)

array([49, 97, 12, 34, 95,  5, 71, 71, 23,  6], dtype=int32)

In [ ]:
np.identity(3) # Create a 3x3 identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### **Array Operation**


In [45]:
a1 = np.arange(12).reshape(3, 4)
a2 = np.arange(12, 24).reshape(3, 4)

a1


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [44]:
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [42]:
#scalar operation

a1 * 2 # Multiply each element by 2



array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [43]:
a1 + a2 # Add two arrays element-wise

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [46]:
a1 > 10 # Compare each element with 10

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True]])

In [47]:
##Vector OperationS


a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [48]:
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [49]:
a1 + a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

### **Functions**

In [50]:
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [51]:
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [52]:
a1.min()

np.int64(0)

In [53]:
a1.max()

np.int64(11)

In [54]:
a2.argmax()

np.int64(11)

In [55]:
a2.argmin()

np.int64(0)

In [56]:
a2.sum()

np.int64(210)

In [57]:
np.sum(a2)

np.int64(210)

In [ ]:
a2.min(axis = 0) # Minimum along the first axis (columns)

array([12, 13, 14, 15])

In [59]:
#mean/median/std/var

np.mean(a1)

np.float64(5.5)

In [60]:
np.mean(a1, axis = 1)

array([1.5, 5.5, 9.5])

In [61]:
np.sin(a1)

array([[ 0.        ,  0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ,  0.6569866 ],
       [ 0.98935825,  0.41211849, -0.54402111, -0.99999021]])

In [62]:
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [63]:
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [68]:
a2 = np.arange(1, 7).reshape(2, 3)
a3 = np.arange(7, 13).reshape(3, 2)
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [69]:
a3


array([[ 7,  8],
       [ 9, 10],
       [11, 12]])

In [70]:

np.dot(a2, a3)

array([[ 58,  64],
       [139, 154]])

In [74]:
b= np.random.random((2, 3))*100
b

array([[97.82159699,  8.86125111, 29.39409134],
       [23.90439757, 51.66116572,  4.59710335]])

In [75]:
np.ceil(b)

array([[98.,  9., 30.],
       [24., 52.,  5.]])

In [76]:
np.floor(b)

array([[97.,  8., 29.],
       [23., 51.,  4.]])

In [77]:
np.round(b)

array([[98.,  9., 29.],
       [24., 52.,  5.]])

### ** Indexing and slicing**

In [80]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3, 4)
a3 = np.arange(8).reshape(2, 2, 2)

In [81]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [82]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [83]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [84]:
a1[0]  # Access the first element of a1

np.int64(0)

In [ ]:
a2[1, 2]   # Access the element at row 1, column 2 of a2


np.int64(3)

In [87]:
a2[2, 3]

np.int64(11)

In [88]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [89]:
a3[1, 0, 1]

np.int64(5)

In [91]:
#slicing
a1[2:5]  # Access elements from index 1 to 4 of a1

array([2, 3, 4])

In [93]:
#itaration

for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [94]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
for i in a2:
    print(i) #prints eache row at a time
    

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [97]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [98]:
for i in a3:
    print(i) #prints each 2D slice of a3

[[0 1]
 [2 3]]
[[4 5]
 [6 7]]


In [ ]:
for i in np.nditer(a2): # convert to 1D
    print(i) #prints each element of a3

0
1
2
3
4
5
6
7
8
9
10
11


In [104]:
for i in np.nditer(a3): #convert to 1D
    print(i) #prints each element of a3

0
1
2
3
4
5
6
7


In [106]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [105]:
#transpose

np.transpose(a2)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [107]:
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [2]:
import numpy as np

In [4]:
arr = np.array([10, 20, 30, 40, 50])
print("Mean: ", np.mean(arr))
print("Median: ", np.median(arr))
print("Standard Deviation: ", np.std(arr))
print("Max: ", np.max(arr))

Mean:  30.0
Median:  30.0
Standard Deviation:  14.142135623730951
Max:  50


In [6]:
arr = np.arange(1, 13).reshape(3, 4)
print("Array:\n", arr)

Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [7]:
identity = np.eye(4)
print("Identity Matrix:\n", identity)

Identity Matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
